/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include "rct.h"
#include <time.h>

int *
obtener_id_1_svc(char **argp, struct svc_req *rqstp)
{
	static int  result;

	srand(time(NULL));
	result = (int) 100.0 * strlen(*argp) * rand();
	printf("Id OK\n");
	return &result;
}

long *
bindate_1_svc(void *argp, struct svc_req *rqstp)
{
	static long timeval; /* must be static */
	timeval = time((long *) 0);
	printf("Time is %ld\n", timeval);
	return &timeval;

}

char **
obtener_respuesta_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	char *mensaje;
	mensaje = "OK";
	result = mensaje; 
	printf("Mensaje Ok\n");
	return &result;
}
