/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rct.h"
#include <time.h>

void
rct_servicio_1(char *host, char *nombre, char *mensaje)
{
	CLIENT *clnt;
	int  *result_1;
	char * obtener_id_1_arg;
	long  *result_2;
	char *bindate_1_arg;
	char * *result_3;
	char * obtener_respuesta_1_arg;
	struct tm *tm;
	char fecha_hora[100];

#ifndef	DEBUG
	clnt = clnt_create (host, RCT_SERVICIO, RCT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	obtener_id_1_arg = nombre;
	result_1 = obtener_id_1(&obtener_id_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Id: %d\n", *result_1 );
	}
	//*bindate_1_arg = NULL;
	result_2 = bindate_1((void*)&bindate_1_arg, clnt);
	if (result_2 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{	//Hace la conversión del time_t generado en el servidor
		tm = localtime(result_2);
		strftime(fecha_hora, 100, "%d/%m/%Y %H:%M:%S %z", tm);
		// formato:  dia/mes/año hora/minutos/segundos uso_horario
		printf("Fecha de envío: %s\n", fecha_hora );
	}
	obtener_respuesta_1_arg = mensaje;
	result_3 = obtener_respuesta_1(&obtener_respuesta_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Mensaje: %s\n", *result_3 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("usage: %s server_host  nombre  mensaje\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rct_servicio_1 (host, argv[2], argv[3]);
exit (0);
}
